= "Fedora and Open Source to open your future in Tech" – _Justin W. Flory_

Talk notes and summary for a guest session I was invited to by link:++https://twitter.com/_dev_nasir_++[Nasir Hussain].


== Audience

* University students: "FOSS Newbies, Developers"
* Set to live stream to Fedora Pakistan Facebook page
** Asked to personalize to this audience


== Selected topics

. About the Fedora Project:
  As a Linux distribution with different Editions and Objectives, and a global community of people who contribute
. How to get involved with the Fedora Project:
  Software, non-software, or both
. How to use Linux and Fedora to launch or improve an I.T. career


== Abstract

Launching a new career in Tech/I.T. is challenging.
There are many things to learn in this fast-paced environment.
So, how can the Fedora Linux project and Open Source Software give you a boost?

Justin W. Flory, a Fedora Project contributor and student from the U.S., explains how Open Source Software helps you get extra experience with international Tech communities while also giving back with your contributions.
He covers three topics:

. How Open Source Software helps you build a Tech career
. How you can get knowledge by giving time
. About the Fedora Project
. How to get involved with the Fedora Project


== Speaker intro

**Short**:

Justin W. Flory is a creative maker.
He is best-known as an open source contributor based in the United States.
Since he was 14, Justin has participated in numerous open source communities and led different initiatives to build sustainable software and communities.

**Long**:

Since 2018, he is a leading member of the LibreCorps program of the FOSS@MAGIC initiative at the Rochester Institute of Technology.
He was the first, full-time co-op placement to work exclusively on community issues for UNICEF Office of Innovation.
This was work he did in concert with UNICEF personnel and Red Hat Open Innovations Lab on UNICEF’s MagicBox effort.
This was an engagement highlighted by Jim Whitehurst, former Red Hat CEO and President of IBM, during one of his Red Hat Summit keynote showcases at Red Hat Summit in 2018.
Since then, Justin led half-day workshops for UNICEF’s Innovation Fund to introduce over 20 international start-up teams to the Open Source way.

Furthermore, Justin is a contributor to the Fedora Project.
In Fedora, he volunteered as team lead of the Community Operations team for four years and was a founding member of the Diversity and Inclusion Team.
He represented Fedora internationally at events and conferences, including FOSDEM, DevConf CZ, All Things Open, OSCAL, and others.


== Speaker notes

=== Introduction

* About me
** Student at the Rochester Institute of Technology
** Open source contributor for the last seven years, making my first source code commits at 14
** Worked at Wall Street trading firms and international humanitarian organizations
* Today, I'd like to talk about Free & Open Source Software and talk about how it can help you launch a new career or build an existing career in tech

=== How Open Source Software helps you build a Tech career [10m]

. Gain new skills
. Make real contributions while you learn new things or build on what you already know
. Meet new people from around the world

=== How you can get knowledge by giving time [10m]

. *Pay-offs on contributing*:
  In it for the long run
. *Volunteering in open source gets you different kinds of knowledge*:
  Tech skills, people skills, collaboration skills
.. Why are all these valuable skills?
.. How can they get you hired?
. *Interactive learning*:
  Make real contributions, successes, and mistakes while you learn
.. Public mistakes are scary, but they are opportunities!

=== About the Fedora Project [10m]

. About the Linux distribution and its relationship to Enterprise
. Very brief history of Fedora
. What does Fedora do today?
  (Editions & Objectives)
. What makes Fedora different from RHEL/CentOS?
.. Community… duh! :wink:

=== How to get involved with the Fedora Project [10m]

. Gradually narrow and filter content down:
.. https://docs.fedoraproject.org/en-US/project/orgchart/[High level organization] (orgchart, orgchart, orgchart!)
.. https://whatcanidoforfedora.org/en/[WCIDFF]
.. https://docs.fedoraproject.org/en-US/fedora-join/[Join SIG]
