= Move Slow and Try Not to Break Each Other (Deb Nicholson)

== Abstract

https://osem.seagl.org/conferences/seagl2020/program/proposals/748[Online at seagl.org].

Sustainable open source starts with building sustainable communities.
If our workplaces and our communities aren't sustainable then our projects won't be either.
Constant chaos and breakneck speeds can only occasionally create sustainable projects, by accident.
The next generation of software production will need to lean into relationship building, mission sharing and strategic planning.
This talk will explore:

* How projects can get ready for the long haul
* Why resiliency starts with inter-dependency
* How slower structures enable stronger communities

Many of us are doing many of the things that help build sustainable projects already, but what if we could be more intentional?
Certain structures and norms can make it hard to implement positive changes even when good ideas come up.
Shared leadership and mission-driven organizations offer solid structures for sustainable communities and sustainable software development.
Mutual respect and humane working conditions are how we'll create a culture that values both experience and institutional memory while encouraging new people and new ideas.
Let's slow down for sustainability!


== Live notes

=== Intro

* Definition of sustainability?
** Word is confusing and has subtle different contexts in different dictionaries
** Shows fragility (and perhaps overuse?) of "sustainable" word
* Deb wants the people to be sustainable.
* On snails and slime
** Let's explore the similarities of snails and Free Software (non-snails)

=== Adherence

* Stick to your goals
* Say you want to do Free Software, and then switch two years later
* Share your mission and goals often
** Give a clear idea of where you headed and where you go
** Attact folks who want to help because of your mission
   (versus in spite of that mission)
* People will want to pitch in, if you have an inspiring vision

=== Social lubrication

* Building relationships
** Build up and down the stack
** Host events with stakeholders and users, invite upstream and downstream and hang out at their events
* Communicate early and often.
** First day you are talking to people should not be the day everything is on fire… preferably
** Get an idea of who does what
* Build relationships with not just extroverts.

=== Recognizing other snails

* Who actually wants to help you build this thing?
** Not just software, but community; in the way you want to build it
* Building a great community with nice people is a limited resource
** *Build in redundancy*:
   Two people can do anything important, access a bank account, know where to find a contact or historical info, etc.
* Let folks walk away for a day, a week, without everything going wrong
** "But you can't leave" doesn't work
** Life happens:
   Start a family, be a caretaker, go to school, take care of self
* Reliable documentation so someone can come in and pick up the gaps
* *Don't be afraid to do less*.
** Project that needs 10 people gets 5 people; do not ask people to double-up!
** Leave opportunities to rearrange plans to adjust for available time and resources
* "Triage with abandon"
* Do not pressure people into burnout by giving them too much work

=== Repulsing predators

* Snail slime repels its predators
* In Free Software, obviously not literal predators who will eat your PM
* But because of how mainstream tech culture is, someone might think they are making a positive contribution
** Not always going to be the case…
** e.g. 10-hour days and working weekends to pull off a project
* Slower, kinder structures
** Requires maintaining boundaries
** People stressed under deadlines / panic-mode; their behavior is impacted in other ways in the team
* *Give people time to be their best selves*
** And, *give _yourself_ time to be your best self*
* Be picky about your clients and partners, when possible
** Narrow in to your target users and audience
** When you are more relaxed, you have time to work on other important aspects of community
* *A little leeway to be extraordinary*
* So, build something amazing or treat people like human beings?
** Terrible question; why not both?

// Aside: I wonder how much of this conversation was inspired from Deb's arrival to OSI… a question I will leave unanswered. :)
