= Open Source 101
Justin W. Flory <contact@jwf.io>
v1.0.0, 2020-05-25

[link=https://creativecommons.org/licenses/by/4.0/]
image::https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg[License: *CC BY 4.0*]

_Open Source 101_ is a crash course in open source that gives the audience practical advice on participating in open source, while also understanding the history of how Free Software started almost 40 years ago.


== Abstract

Class is _in_ session!
Today's topics:

* What is open source?
* How can open source help me launch a tech / I.T. career?
* How is open source useful for me as a writer or designer?
* Why getting involved is usually better than starting new

This is a practical session to give a background on what open source is all about and to learn some history of why open source matters more today than it ever has before.
Why have U.S. Wall Street, Silicon Valley, and big technology and financial institutions placed big bets on open source?
And is there a way for open source to help you with building a tech career?
This talk addresses these questions in detail to help the audience understand why open source is widely recognized and practical, and provide practical tips on how to get involved.

You won't believe the two things nobody ever told you before about choosing an open source community!


== Outline

. What is open source?
. Open source beyond software
. How to contribute to open source
. Meet Fedora
