= Septima Clark

Research for biography essay on the life of Septima Poinsette Clark.

== Research questions

=== Where and when was your black feminist born? (country, city, county, etc.)

* (*Neumann*) 1898 May 3 in Charleston, South Carolina

=== Who were their parents and what were they like? (jobs, personality, finances, etc.)

* (*Charron-Cline*) Peter Porcher Poinsette: father
** Grew up a slave in Georgetown, South Carolina
** Primarily took his master's children to school and back: Often noted the irony of taking the kids there and not being able to learn how to write his own name
** When his mother died, they waited overnight for someone to make a coffin for her, then went and buried here in the night because there was not time in the day
** He recounted these stories not in a violent tone, according to Clark
** Irony of his slavery in supporting the soldiers fighting to keep him a slave
** After slavery, he worked job in a harbor and frequently traveled into West Indies and other places ships went; there he met Clark's mother and married in Jacksonville, Florida
** After WWI: Became custodian at United Service Organizations and had to sign his name on checks; that's when he finally learned how to sign his name
* (*Charron-Cline*) Victoria Warren Anderson Poinsette: mother
** Reared in Haiti: lost her mother as a girl and was raised by her older brother and three siblings after in Haiti
** Learned to read and write in Haiti
** Boasted she was never a slave: Washed and ironed at home but never did hard labor (?)
** In Clark's life, she was the "boss of the house" and she was the one you had to listen to: she did most of the whipping
*** *Strong overlap with "Shadow of the Whip"*
*** "I tried to correct her one morning when she was telling her sister something; she slapped my teeth out of the front of my mouth and made me wash it out with some salt and water and go right on to Sunday school."
** Clark appreciated her mother's courage because she spoke against segregation to her children, when it was still mostly unopposed

=== List and explain notable childhood experiences in their life. (must find at least 1)

* (*Charron-Cline*): Father's desire for his children to have an education
** "When we were children, the one thing [my father] wanted was for us to have an education.
   This was the only thing that I know he would whip you for: if you didn't want to go to school.
   There were times we didn't want to go.
   I cried one morning I didn't want to go to that school, and he whipped me with a strap and then took me down there."
* (*Charron-Cline*): First experience with political organizing
** "In all the public schools [in Charleston], you know, we had white teachers teaching black children.
   In 1919, we went door-to-door to ask people if they wanted black teachers to teach their children.
   That was my first real political thing.
   Because the lawmakers said that only the mulattoes wanted these jobs, and they didn't think that the domestic workers and the chauffeurs and the garbage people and the longshoremen wanted black teachers.
   So we had to do a door-to-door thing to get black teachers to teach their children.
   And in 1920 we got them.
   Oh, that thing had been coming a long time, but we hadn't gotten to the place where we felt as if we could get the signatures before.
   I took my students along with me, and we got these signatures.
   Some would be across the street, and then I'd do it on the other side, and that's how we did it."

=== Describe the black feminist's education experiences and background.

* (*Neumann*) Graduated from Avery Normal Institute in 1916
* (*Neumann*) Collegiate career:
** 1942: Earned B.A. in English from Benedict College
** 1946: Earned M.A. from Hampton Institute

=== Where did they live when they wrote/spoke/worked? Did they travel? Describe and explain.

* (*Charron-Cline*) Mostly in South Carolina, until ostracized to Tennessee
** Befriending the Warings in 1950 and joining them in the call for immediate integration was unpopular in Jim Crow S.C.
** Moved to Tennessee as full-time teacher at Highlander Folk School

=== Describe the economic, social, and political climate experienced by the black feminist during the time period in which they advocated for social justice.

* (*Charron-Cline*) Public school teacher and civic organizer in Jim Crow South
** Teaching citizenship that linked self-help to politics
*** Learn to read and write to pass literacy tests
*** How to create household budget
*** Balance a checkbook
*** Apply for Social Security benefits
* (*Charron-Cline*) Women empowered through role of teaching, something Clark realized
** "First, when compared to losing one's job, facing eviction from a white landlord, or risking one's life by participating in direct action campaigns, teaching adults to read and write appeared a relatively safe entry point into the Movement."
* (*Charron-Cline*) Violence and nonviolence
//**
* (*Charron-Cline*)

=== What jobs did the black feminist have during their lifetime?

* (*Neumann*) Early career as a teacher
** 1916: Accepted teaching position on John's Island since black teachers banned from public schools of Charleston
** 1919: Returned to Charleston to teach at Avery Normal
** 1920s-1930s: Taught as public school teacher in Columbia and Charleston
* (*Neumann*) 1954-1961: Taught citizenship education at Highlander Folk School in Monteagle, Tennessee
** (*Charron-Cline*) Highlander Folk School: Interracial adult education center where activists gathered to devise solutions for problems in their communities
* (*Neumann*) 1961-1970: Director of Education, Southern Christian Leadership Council (SCLC)

=== Describe relationships experienced by the black feminist. (marriage, affair, children, friends, etc.)

* (*Neumann*) 1920: Married seaman Nerie Clark
** Infant daughter died in 1923; infant son was only surviving child
** Nerie Clark died in 1925
* (*Charron-Cline*) On her experience in marriage
** Death of infant was punishment manifested as the will of God according to religious laws she learned
** Marriage to her husband was always against her mother's wishes: "She said, "You're marrying a man you don't know," because anybody out of the state was somebody that she didn't know."
** Husband left after the baby's death; nearly committed suicide until she was stopped by her brother
* (*Charron-Cline*) Thoughts on re-marrying
** "I don't think I would have been able [to accomplish] very much.
   I'm very sure that a man wouldn't put up with it.
   See, the way I had to go, sometimes I made three cities in a day, working for SCLC [Southern Christian Leadership Conference] and the Highlander Folk School.
   Maybe I'd speak in Seattle this morning, and I'll hop a plane and I'd get to Calgary, and I'll hop another plane and I'd go to Alberta.
   A man wouldn't hardly put up with that.
   I didn't get back here but just around Christmas, maybe I'd have one or two days.
   I was gone all the time."

=== What religions, political issues, or political leaders influenced them?

* (*Neumann*) 1919: Joined National Association for the Advance of Colored People (NAACP)
** 1920: Successfully campaigned for state law tha allowed blacks to teach in Charleston black public schools
* (*Charron-Cline*) Elizabeth Waring's speech to the African American branch of the Charleston YWCA in 1950
** Mrs. Waring was second wife of local Judge Waring
** Controversial as one of the few/only white families in Charleston who spoke up against segregation and racism
** "To be unmercifully truthful, I don't really feel that Mrs. Waring had that much knowledge of the life of blacks.
   It was Judge Waring's influence on her—that's what I think—that imparted to her the fact that "I would like to change things."
   She was like my mother, very high-strung, and very angry over things.
   She got angry with me when I said that she was vitriolic.
   She didn't like that.
   But it was true."
** *Trend towards nonviolence over Black Power?*
   Hard to read how this influenced her.

=== What gender, racial, or social issues influenced them?

* (*Neumann*) 1954: Lost teaching role and pension because of role as Charleston NAACP membership chair
** S.C. legislature passed law that no city or state employee could be affiliated with a civil rights organization
** She refused to renounce her membership
* (*Charron-Cline*) Spent most of her life working within women-centered networks
** Informed her recognition of women's roles in Civil Rights goals, and also why they did not receive recognition

=== Who were the black feminist's contemporaries? How did the contemporaries influence them?

* (*Charron-Cline*) 1961 transfer of the Citizenship Schools to the SCLC
** Clark arrested in T.N. in 1959 and Highlander Folk School closed down
** Dr. Martin Luther King reached out to Clark and invited her and her Citizenship Education Program to Atlanta
** Deep fear in the South about Highlander because of legacy of integration at Highlander (whites and blacks lived and worked together there)
** "We didn't need anyone with a high school education, nor did we need anyone with a college education.
   We just wanted to have a community person, so that the illiterates would feel comfortable.
   They had to also promise that they would go back to the community and open up a school, and they were supposed to teach two nights a week, two hours each night."

=== What means of public intervention was predominately utilized by the black feminist?

* (*Neumann*) Proponent of nonviolence
* (*Charron-Cline*) Empowerment through education
** Early leader in creating Citizenship Schools
** Prepared network of grassroots teachers in week-long training sessions on topics like:
*** How to recruit students
*** Gauge educational levels
*** Develop lesson plans
** Also taught essential information to participating in public life:
*** Location/hours of voter registration office
*** What healthcare and employment opportunities were available in their communities
** Curriculum consistently developed to new developments in Civil Rights Movement
** "Training sessions and teaching classes afforded grassroots African American women the opportunity to evaluate the local problems they deemed most important while the Movement itself provided a vehicle for addressing them."


== Additional information

* Strong overlap with Frederick Douglass's pause of advocating for women's rights in favor of getting the 15th Amendment; at the time, a polarizing action


== Sources

* Charron, Katherine Mellen.
  Center for the Study of the American South.
  _Freedom's Teacher: The Life of Septima Clark._
  University of North Carolina Press, Chapel Hill, 2009, doi:10.5149/9780807898468_charron.
* Charron, Katherine M., and David P. Cline.
  ""I Train the People to do their Own Talking": Septima Clark and Women in the Civil Rights Movement."
  _Southern Cultures_, vol. 16, no. 2, 2010, pp. 31-52,117.
* Neumann, Caryn E.
  "Clark, Septima."
  _Encyclopedia of Women and American Politics_, Lynne E. Ford, Facts On File, 2nd edition, 2014.
  Accessed 28 Feb. 2020.
