= Self-Organising System

https://www.extinctionrebellion.be/en/self-organising-system/[From Extinction Rebellion Belgium's website.]

The Self-Organising System (SOS) enables us to harness collective wisdom, while remaining agile and able to respond quickly to emerging situations.
This is how it works.


== Distributed authority

* People fill roles with defined mandates (purpose plus domain plus accountabilities).
* They have full authority to make decisions and to take action within that mandate.
* When making a decision from their role, people are responsible for seeking input from those with experience in the area or those affected by it.


== Self-Organising circles

* Each circle (or team) has its own mandate and can define and refine its roles.
* For large roles, the circle may create a sub-circle, which will in turn self-organise.
* This circle structure widens out to the Anchor Circle which contains all circles.
* Consent and linking ensure that no individual has power over another, and mitigate the negative features of a hierarchical structure.
* Each level of the structure is slightly further removed from the minute det and takes a broader view regarding resource use, purpose, and priorities.


== Linking structure

* External coordinators attend meetings of super-circles as equal members.
* This gives every sub-circle equal power to raise objections during decision-making in the wider circle, if they create or change roles.


== How power is decentralised

* Authority is distributed into roles and circles using a collective decision-making process.
* Mandates empower roles to make operational decisions.
* To add or change a role or (sub)circle, a member presents a proposal to resolve an issue, referred to as a tension, and each member of the circle has the opportunity to object.
* Objections are encouraged, as they represent important information that can be integrated to improve the proposal, before it is either accepted or withdrawn.
* The aim is to develop a workable proposal which allows movement forward.
* The decision can be revisited later on.
  It doesn’t have to be perfect first time.


== Radical transparency

* The roles and circles should be kept up-to-date and visible for all.
* This allows every member to discover the structure and to contact whoever they need to when making decisions day-to-day.
* Minutes, projects, and other relevant documents should also be transparent, so that the whole organism has insight into the history of each part.
